In [18]:
import pandas as pd
from sqlalchemy import create_engine

# Ustawienia połączenia z bazą danych
db_config = {
    'uri': "postgresql+psycopg2://postgres:ftZDAzKbfSK9WXh@localhost:5432/bimbasiqul"  # Twój ciąg połączenia
}

# Tworzenie połączenia
engine = create_engine(db_config['uri'])

# Sprawdzanie połączenia
try:
    with engine.connect() as conn:
        print("Połączenie z bazą danych zostało nawiązane pomyślnie!")
except Exception as e:
    print(f"Błąd podczas łączenia z bazą danych: {e}")

Połączenie z bazą danych zostało nawiązane pomyślnie!

In [19]:
# Zapytanie SQL
query = "SELECT * FROM daily_report;"  # Dopasuj do swojej tabeli
try:
    full_view = pd.read_sql(query, engine)
except Exception as e:
    print(f"Błąd podczas pobierania danych: {e}")

In [20]:
full_view

,entity_id,trip_id,route_id,route_short_name,stop_sequence,arrival_delay,local_timestamp,latitude,longitude,stop_id,...,route_type,version_id,service_start_date,service_end_date,direction_id,trip_headsign,trip_start_time,trip_end_time,route_avg_delay,route_stop_avg_delay
0,9110,1_4950175^+,901,901,0,20,2024-12-10 04:10:26,52.488770,16.854469,3378,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,04:10:00,04:37:00,174.278583,153.121212
1,9110,1_4950175^+,901,901,0,39,2024-12-10 04:10:46,52.488770,16.854469,3378,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,04:10:00,04:37:00,174.278583,153.121212
2,9110,1_4950175^+,901,901,0,60,2024-12-10 04:11:06,52.488770,16.854469,3378,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,04:10:00,04:37:00,174.278583,153.121212
3,9110,1_4950175^+,901,901,0,79,2024-12-10 04:11:26,52.488770,16.854469,3378,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,04:10:00,04:37:00,174.278583,153.121212
4,9110,1_4950175^+,901,901,1,96,2024-12-10 04:11:42,52.488831,16.854740,4006,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,04:10:00,04:37:00,174.278583,110.402439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986655,1774,5_8049186^+,189,189,0,-1159,2024-12-09 19:31:45,52.366310,16.930321,1393,...,3,1,2024-12-06,2024-12-22,1,Starołęka PKM,19:51:00,19:51:00,84.923335,65.345455
1986656,1774,5_8049186^+,189,189,0,-1138,2024-12-09 19:32:06,52.366310,16.930321,1393,...,3,1,2024-12-06,2024-12-22,1,Starołęka PKM,19:51:00,19:51:00,84.923335,65.345455
1986657,1774,5_8049186^+,189,189,0,-1119,2024-12-09 19:32:26,52.366310,16.930321,1393,...,3,1,2024-12-06,2024-12-22,1,Starołęka PKM,19:51:00,19:51:00,84.923335,65.345455
1986658,1774,5_8049186^+,189,189,0,-1079,2024-12-09 19:33:02,52.366310,16.930321,1393,...,3,1,2024-12-06,2024-12-22,1,Starołęka PKM,19:51:00,19:51:00,84.923335,65.345455
1986659,1774,5_8049186^+,189,189,0,-1058,2024-12-09 19:33:22,52.366310,16.930321,1393,...,3,1,2024-12-06,2024-12-22,1,Starołęka PKM,19:51:00,19:51:00,84.923335,65.345455

In [44]:
full_view.sample(10)

,entity_id,trip_id,route_id,route_short_name,stop_sequence,arrival_delay,local_timestamp,latitude,longitude,stop_id,...,route_type,version_id,service_start_date,service_end_date,direction_id,trip_headsign,trip_start_time,trip_end_time,route_avg_delay,route_stop_avg_delay
1164656,1621,5_8043622^+,166,166,14,185,2024-12-09 14:38:24,52.380981,17.002529,3862,...,3,1,2024-12-06,2024-12-22,1,Zieliniec,14:12:00,14:53:00,116.749064,125.349810
804379,553,5_8008268^N+,18,18,0,-547,2024-12-09 06:25:00,52.381950,17.001230,221,...,0,1,2024-12-06,2024-12-22,0,Ogrody,06:34:00,07:11:00,112.637036,NaN
845847,507,5_8008570^N+,24,24,17,19,2024-12-09 21:30:22,52.407768,16.913210,86,...,0,1,2024-12-06,2024-12-22,1,Górczyn PKM,21:06:00,21:43:00,-68.192159,8.532710
348632,8030,5_7917769^S+,825,825,13,497,2024-12-09 14:32:14,52.491711,16.653130,2104,...,3,1,2024-12-06,2024-12-22,1,Góra/Pętla,14:05:00,14:29:00,168.864440,261.900000
518245,419,5_8006325^N+,11,11,10,-56,2024-12-09 15:25:08,52.389881,16.894690,1630,...,0,1,2024-12-06,2024-12-22,1,Piątkowska,15:13:00,15:52:00,55.246492,23.251781
1001528,443,5_8009502^N+,7,7,16,106,2024-12-09 15:17:51,52.410210,16.955799,134,...,0,1,2024-12-06,2024-12-22,0,Ogrody,14:54:00,15:49:00,81.563562,65.471795
509125,918,5_8006280^N+,10,10,14,133,2024-12-09 20:56:24,52.415581,16.918480,8,...,0,1,2024-12-06,2024-12-22,0,Dębiec PKM,20:38:00,21:15:00,197.302110,36.403077
1871333,1769,5_8048211^+,189,189,5,21,2024-12-09 13:52:36,52.359680,16.940880,3236,...,3,1,2024-12-06,2024-12-22,1,Starołęka PKM,13:49:00,14:03:00,84.923335,59.789298
436306,7037,5_7919550^S+,729,729,14,73,2024-12-09 14:10:18,52.397171,16.802240,2913,...,3,1,2024-12-06,2024-12-22,1,Dopiewo/Dworzec Kolejowy,13:52:00,14:45:00,219.015616,54.777251
860276,934,5_8008653^N+,3,3,29,166,2024-12-09 19:27:57,52.392208,16.973141,211,...,0,1,2024-12-06,2024-12-22,1,Unii Lubelskiej,18:49:00,19:34:00,31.443954,129.288136

In [45]:
# Zakładamy, że masz DataFrame df i linię, którą chcesz wybrać (np. route_id == '901')
selected_line = '193'

# Filtrowanie danych dla wybranej linii
df_selected_line = full_view[full_view['route_id'] == selected_line]

In [46]:
df_selected_line.sample(10)

,entity_id,trip_id,route_id,route_short_name,stop_sequence,arrival_delay,local_timestamp,latitude,longitude,stop_id,...,route_type,version_id,service_start_date,service_end_date,direction_id,trip_headsign,trip_start_time,trip_end_time,route_avg_delay,route_stop_avg_delay
1834831,1908,5_8047973^+,193,193,11,226,2024-12-09 08:57:57,52.401772,16.865089,773,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,08:38:00,09:31:00,133.216998,101.069869
1840329,1020,5_8047997^+,193,193,29,26,2024-12-09 06:09:31,52.458229,16.904350,369,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,05:23:00,06:14:00,133.216998,181.784153
1289875,1201,5_8044577^+,193,193,16,266,2024-12-09 18:57:55,52.420380,16.893940,1451,...,3,1,2024-12-06,2024-12-22,0,Górczyn PKM,18:33:00,19:28:00,133.216998,155.588571
1847621,1011,5_8048047^+,193,193,31,61,2024-12-09 05:37:53,52.465488,16.906309,377,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,05:01:00,05:39:00,133.216998,280.231362
1827512,1027,5_8047946^+,193,193,30,148,2024-12-09 19:07:33,52.387100,16.858841,1064,...,3,1,2024-12-06,2024-12-22,0,Górczyn PKM,18:20:00,19:15:00,133.216998,241.619968
1294838,1904,5_8044607^+,193,193,19,68,2024-12-09 07:42:12,52.416721,16.892349,778,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,07:08:00,08:02:00,133.216998,136.716918
1861119,1202,5_8048127^+,193,193,0,-199,2024-12-09 06:14:46,52.465019,16.916161,381,...,3,1,2024-12-06,2024-12-22,0,Górczyn PKM,06:18:00,07:13:00,133.216998,NaN
1297174,1904,5_8044615^+,193,193,13,18,2024-12-09 18:02:34,52.409019,16.865530,632,...,3,1,2024-12-06,2024-12-22,1,Os. Sobieskiego,17:39:00,18:33:00,133.216998,-3.345024
1826212,1027,5_8047942^+,193,193,5,42,2024-12-09 12:53:54,52.456390,16.904190,365,...,3,1,2024-12-06,2024-12-22,0,Górczyn PKM,12:48:00,13:45:00,133.216998,73.691288
1836290,1908,5_8047978^+,193,193,11,261,2024-12-09 15:20:49,52.436211,16.912170,789,...,3,1,2024-12-06,2024-12-22,0,Górczyn PKM,15:03:00,16:04:00,133.216998,118.900506